### ISSUE TITLE
*FEATURE REQUEST* - Fan Script Integration (RockPro64)

### ISSUE THREAD

**Issue by kycfree1** [monero-ecosystem/PiNode-XMR#81] opened 2022-07-22 09:57 UTC
The default 20mm Pine64 heatsink does not seem to be adequate for the initial setup, update & synchronisation process with temps registered up to 76c before I terminated my RockPro64 setup (using image).

Use of a pine64 heatsink mounted fan (40x40x10) solves this when connected to the 2 pin fan port of the RockPro64, however due to noise would be great for an optional temp/speed controlled fan script to be included in the tools section for easy install.

For example; 45c > 25% speed, 50c > 50% speed, 55c > 75% speed, 60c > 100% speed.

**Comment by shermand100** [comment] 2022-07-25 12:02
I feel the example you've quoted exactly fits:

https://github.com/tuxd3v/ats

Which can easily be added into the 'System Settings' Menu.
I've installed this onto my RockPro64 this morning and can see it controls the fan as expected.

Hardware:
RockPro64
[Fan for Metal NAS case ](https://pine64.com/product/fan-for-rockpro64-metal-desktop-nas-casing/)
[Metal RockPro64 NAS case](https://pine64.com/product/rockpro64-metal-desktop-nas-casing/)

Is this what you're suggesting?

**Comment by kycfree1** [comment] 2022-07-25 12:23
Yes this would be great. 
I also tried to install this same package and failed miserably.

If a one click install is not something which you would want to integrate, then perhaps instead a guide that those unable to figure it out for themselves could easily follow.

👍🏻

**Comment by shermand100** [comment] 2022-07-25 12:45
If you want to test it:

> sudo apt-get install lua5.3 lua5.3-dev gcc make -y
> git clone https://github.com/tuxd3v/ats.git
> cd ats
> make
> sudo make install

It should be running from that, check with:
`sudo systemctl status ats`

I don't mind adding it as an option as it should eb applicable to all devices that have an onboard PWM fan connector, not just RockPro64. Some of the newer NanoPi devices have this connector too.

**Comment by kycfree1** [comment] 2022-07-25 13:05
Excellent. So I just SSH in as normal as pinode@192.168.x.xx then exit back to command line and enter the commands how you typed?

I think this would be a valuable addition to the software, especially for owners using boards where a fan is essential.

Thank you

**Comment by shermand100** [comment] 2022-07-25 13:29
Yeah exactly, give it a go and see if you like the behaviour.
Obviously I didn't create that but may be able to fork and tweak if needed.

Then I'd script those commands into the setup menu if it seems suitable.

**Comment by kycfree1** [comment] 2022-07-25 13:36
Legend, I'll plug in a fan & give it a go later.
Have a big box of fans.

To clarify the pwm port is the 3 pin port between the two 2 pin ports on the rp64, requiring a 3 wire fan?

**Comment by shermand100** [comment] 2022-07-25 13:51
Nope, 2 pin fan socket. Item (4) on the board layout wiki:
https://wiki.pine64.org/wiki/ROCKPro64

**Comment by shermand100** [comment] 2022-08-01 01:09
The fan curve follows the ats default:
https://github.com/tuxd3v/ats#characteristics

On my RockPro64 I have the NAS case fan attached the PWM header controlled by this.
I found that with no intervention (no ATS) the fan by default spins at max 24/7 (value 255).
I personally prefer not to use ATS and instead set the fan speed value to 80, which is silent and keep the CPU <55 on load.

I find this ATS doesn't run the fan most of the time and perhaps 20 seconds run time per 2 minutes it runs at 70% which I then notice. I'd prefer silent running speeds.


The issue is I can't tweak this without another user plugging a CPU fan (rather than case fan) to those pins. Their different use case will require a different fan profile.

**Comment by shermand100** [comment] 2022-08-01 17:11
Sure. I'm just working on improving the updater scripts so will merge this in the same update. Probably v5.22.08.

**Comment by shermand100** [comment] 2022-10-05 12:38
Feature merged.

**Closed by shermand100** 2022-10-05 12:38 UTC
Labels: enhancement, Improvement incorporated, Ready to Merge
